//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
/*
namespace foro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buzon_entrada
    {
        public buzon_entrada()
        {
            this.mensaje_privado = new HashSet<mensaje_privado>();
        }
    
        public int id_buzon { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> mensajes { get; set; }
        public Nullable<int> mensajes_sin_leer { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<mensaje_privado> mensaje_privado { get; set; }
    }
}
*/