//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_usuario
    {
        public grupo_usuario()
        {
         //   this.usuario = new HashSet<usuario>();
        }
    
        public int id_grupo { get; set; }
        public string nombre_grupo { get; set; }
        public Nullable<bool> creacion_categoria { get; set; }
        public Nullable<bool> publicar_comentario { get; set; }
        public Nullable<bool> eliminar_categoria { get; set; }
        public Nullable<bool> eliminar_tema { get; set; }
        public Nullable<bool> eliminar_mensaje { get; set; }
        public Nullable<bool> editar_mensaje { get; set; }
        public Nullable<bool> editar_usuario { get; set; }
    
   //     public virtual ICollection<usuario> usuario { get; set; }
    }
}
