//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
/*
namespace foro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje_privado
    {
        public int id_mensaje { get; set; }
        public Nullable<int> id_remitente { get; set; }
        public Nullable<int> id_buzon { get; set; }
        public Nullable<bool> leido { get; set; }
        public string mensaje { get; set; }
        public string fecha_de_envio { get; set; }
    
        public virtual buzon_entrada buzon_entrada { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
*/