//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
/*
namespace foro2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XEEntities : DbContext
    {
        public XEEntities()
            : base("name=XEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buzon_entrada> buzon_entrada { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<grupo_usuario> grupo_usuario { get; set; }
        public virtual DbSet<mensaje_privado> mensaje_privado { get; set; }
        public virtual DbSet<prueba> prueba { get; set; }
        public virtual DbSet<tema> tema { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }

        public System.Data.Entity.DbSet<foro2.Models.LoginViewModel> LoginViewModels { get; set; }
    }
}
*/