//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.buzon_entrada = new HashSet<buzon_entrada>();
            this.comentario = new HashSet<comentario>();
            this.mensaje_privado = new HashSet<mensaje_privado>();
            this.tema = new HashSet<tema>();
        }
    
        public int id_usuario { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public string nombre { get; set; }
        public string contrasenna { get; set; }
        public Nullable<int> cantidad_comentarios { get; set; }
        public string avatar_url { get; set; }
        public string fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string fecha_registro { get; set; }
    
        public virtual ICollection<buzon_entrada> buzon_entrada { get; set; }
        public virtual ICollection<comentario> comentario { get; set; }
        public virtual grupo_usuario grupo_usuario { get; set; }
        public virtual ICollection<mensaje_privado> mensaje_privado { get; set; }
        public virtual ICollection<tema> tema { get; set; }
    }
}
